package com.openclassrooms.chatop.api.mapper;

import com.openclassrooms.chatop.api.dto.MessageDTO;
import com.openclassrooms.chatop.api.dto.request.MessageRequest.CreateMessageRequest;
import com.openclassrooms.chatop.api.model.Message;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * MapStruct mapper for Message entity to MessageDTO conversions.
 * This interface automatically generates the implementation at compile time.
 */
@Mapper
public interface MessageMapper {

    MessageMapper INSTANCE = Mappers.getMapper(MessageMapper.class);

    // -----------------------------
    // Entity -> DTO
    // -----------------------------

    @Mapping(source = "rental.id", target = "rental_id")
    @Mapping(source = "user.id", target = "user_id")
    @Mapping(source = "createdAt", target = "created_at")
    @Mapping(source = "updatedAt", target = "updated_at")
    MessageDTO toDto(Message message);

    // -----------------------------
    // DTO -> Entity
    // -----------------------------

    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "rental", ignore = true) // Set manually in service
    @Mapping(target = "user", ignore = true) // Set manually in service
    @Mapping(target = "createdAt", ignore = true) // Managed by @CreationTimestamp
    @Mapping(target = "updatedAt", ignore = true) // Managed by @UpdateTimestamp
    Message toEntity(CreateMessageRequest request);
}
